### ISSUE TITLE
TODO New recipes

### ISSUE THREAD

**Issue by rodion-arr** [rodion-arr/bitrix-notes#1]
D7 examples
- [x] Cashing
- [x] Application object
- [x] Context object
- [x] File operations
- [x] Basket
- [x] Order
- [x] HTTP
- [x] Order admin page customization
- [x] Ошибка проверки источника запроса. Обновите модуль обмена.
- [x] CSV writing
- [x] BX_SUPPORT_MODE=Y

**Comment by rodion-arr** [comment]
list release - https://github.com/rodion-arr/bitrix-notes/commit/c9b0683f2766bf63851bfbf368487f1ca5e6a4bb
