### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rodion-arr** [rodion-arr/bitrix-notes#2]
- [ ] Composer PSR-4 autoloading example
- [ ] Display errors - http://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display
- [ ] `<script data-skip-moving="true">`
- [ ] Add examples from http://dev.1c-bitrix.ru/community/blogs/vws/14238.php
- [ ] custom admin page
